### ISSUE TITLE
NoUnarmedCombat causing errors in another mod: BowPlugin

### ISSUE THREAD

**Issue by ZenDragonX** [Terrenteller/ValheimMods#3] opened 2023-03-25 06:21 UTC
Hi, I don't know if this problem is caused by your mod or the BowPlugin mod but when NoUnarmedCombat is installed it is causing BowPlugin to throw a lot of errors in the console when switching between the build hammer and the bow or when pressing R to put away the bow while drawing.  I realize that maybe the problem is in the other mod but I wanted to let you know in case there was an internal conflict between the two because the problem only happens in BowPlugin when your mod is installed.

**Comment by Terrenteller** [comment] 2023-03-26 17:50
Definitely caused by us returning `null` from `Humanoid.GetCurrentWeapon()` outside the code path we need it to be `null`. This will be solved with #2.

**Comment by Terrenteller** [comment] 2023-03-26 18:12
Fixed with 4b54b19e69ea1ba88eb6c2ca28d488bcec826340. Thank you for the report.

**Closed by Terrenteller** 2023-03-26 18:12 UTC
Labels: bug
